In [1]:
import pandas as pd
dataset_prep = pd.read_csv(r"/home/srodriguezc/Simulador_de_compra_venta_de_acciones/Data/Merged/Dataset_final.csv")

In [2]:
dataset_prep.head()

,Date,Open,High,Low,Close,Adj Close,Volume,Ticker,dd,mm,...,activity_act,ticker,fiscalDateEnding,ebitda,netIncome,reportedEPS,estimatedEPS,surprise,quarter_label_dr,month
0,25-08-2020,124.697502,125.180000,123.052498,124.824997,121.419495,211495600.0,AAPL,25,8,...,Reduce,AAPL,2020-09-30,1.823700e+10,1.267300e+10,0.73,0.70,0.03,Q3 2020,9.0
1,02-10-2020,112.889999,115.370003,112.220001,113.019997,109.936562,144712000.0,AAPL,2,10,...,Reduce,AAPL,2020-12-31,3.688300e+10,2.875500e+10,1.68,1.42,0.26,Q4 2020,12.0
2,02-10-2020,112.889999,115.370003,112.220001,113.019997,109.936562,144712000.0,AAPL,2,10,...,Buy,AAPL,2020-12-31,3.688300e+10,2.875500e+10,1.68,1.42,0.26,Q4 2020,12.0
3,09-10-2020,115.279999,117.000000,114.919998,116.970001,113.778809,100506900.0,AAPL,9,10,...,Reduce,AAPL,2020-12-31,3.688300e+10,2.875500e+10,1.68,1.42,0.26,Q4 2020,12.0
4,09-10-2020,115.279999,117.000000,114.919998,116.970001,113.778809,100506900.0,AAPL,9,10,...,Buy,AAPL,2020-12-31,3.688300e+10,2.875500e+10,1.68,1.42,0.26,Q4 2020,12.0

In [3]:
columnas_eliminadas = ['Price', 'High', 'Low', 'Close', 'dd', 'mm', 'yyyy', 'Trade Date', 'Insider Name', 'Title', 'Value', 'title_base', 'title_norm', 'estandar_corr', 'History', 'Stock', 'Activity', 'Share change', '% change to portfolio', 'nombre_ticker', 'ticker', 'fiscalDateEnding', 'quarter_label', 'month', 'reportedEPS', 'estimatedEPS', 'quarter_label_dr', 'Ticker_oi', 'Ticker_dr']

dataset_prep = dataset_prep.drop(columns=columnas_eliminadas, errors='ignore')

In [4]:
dataset_prep.head()

,Date,Open,Adj Close,Volume,Ticker,Trade Type,Qty,Owned,ΔOwn,calificacion,quarter_label_oi,source_file,activity_porc,activity_act,ebitda,netIncome,surprise
0,25-08-2020,124.697502,121.419495,211495600.0,AAPL,S,-265160.0,837374.0,-24.0,1.0,Q3 2020,BRK,0.0370,Reduce,1.823700e+10,1.267300e+10,0.03
1,02-10-2020,112.889999,109.936562,144712000.0,AAPL,S,-257343.0,489260.0,-34.0,1.0,Q4 2020,BRK,0.0605,Reduce,3.688300e+10,2.875500e+10,0.26
2,02-10-2020,112.889999,109.936562,144712000.0,AAPL,S,-257343.0,489260.0,-34.0,1.0,Q4 2020,HC,1.0000,Buy,3.688300e+10,2.875500e+10,0.26
3,09-10-2020,115.279999,113.778809,100506900.0,AAPL,S,-243431.0,110272.0,-69.0,1.0,Q4 2020,BRK,0.0605,Reduce,3.688300e+10,2.875500e+10,0.26
4,09-10-2020,115.279999,113.778809,100506900.0,AAPL,S,-243431.0,110272.0,-69.0,1.0,Q4 2020,HC,1.0000,Buy,3.688300e+10,2.875500e+10,0.26

In [5]:
columnas_orden = ['Date', 'quarter_label_oi', 'Ticker', 'source_file']
# Crear el nuevo orden (primero las definidas, luego el resto en su orden original)
nueva_estructura = columnas_orden + [col for col in dataset_prep.columns if col not in columnas_orden]

# Reordenar sobrescribiendo el mismo DataFrame
dataset_prep = dataset_prep[nueva_estructura]

columnas_cambio_nombre = {'quarter_label_oi': 'quarter - year', 'source_file': 'nombre_holding', 'calificacion' : 'insider_rating', 'surprise' : 'eps_surprise'}

dataset_prep = dataset_prep.rename(columns=columnas_cambio_nombre)

dataset_prep

,Date,quarter - year,Ticker,nombre_holding,Open,Adj Close,Volume,Trade Type,Qty,Owned,ΔOwn,insider_rating,activity_porc,activity_act,ebitda,netIncome,eps_surprise
0,25-08-2020,Q3 2020,AAPL,BRK,124.697502,121.419495,211495600.0,S,-265160.0,837374.0,-24.0,1.0,0.0370,Reduce,1.823700e+10,1.267300e+10,0.03
1,02-10-2020,Q4 2020,AAPL,BRK,112.889999,109.936562,144712000.0,S,-257343.0,489260.0,-34.0,1.0,0.0605,Reduce,3.688300e+10,2.875500e+10,0.26
2,02-10-2020,Q4 2020,AAPL,HC,112.889999,109.936562,144712000.0,S,-257343.0,489260.0,-34.0,1.0,1.0000,Buy,3.688300e+10,2.875500e+10,0.26
3,09-10-2020,Q4 2020,AAPL,BRK,115.279999,113.778809,100506900.0,S,-243431.0,110272.0,-69.0,1.0,0.0605,Reduce,3.688300e+10,2.875500e+10,0.26
4,09-10-2020,Q4 2020,AAPL,HC,115.279999,113.778809,100506900.0,S,-243431.0,110272.0,-69.0,1.0,1.0000,Buy,3.688300e+10,2.875500e+10,0.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10871,11-02-2025,Q1 2025,ZTS,FS,171.179993,173.124924,2309400.0,S,-326.0,16919.0,-2.0,1.0,10.2018,Add,9.880000e+08,6.310000e+08,0.08
10872,19-02-2025,Q1 2025,ZTS,FS,156.539993,155.592926,4015300.0,S,-382.0,95006.0,0.0,1.0,10.2018,Add,9.880000e+08,6.310000e+08,0.08
10873,10-03-2025,Q1 2025,ZTS,FS,169.649994,170.651581,3183800.0,S,-326.0,16593.0,-2.0,1.0,10.2018,Add,9.880000e+08,6.310000e+08,0.08
10874,11-03-2025,Q1 2025,ZTS,FS,170.619995,163.291107,3511400.0,S,-1210.0,11245.0,-10.0,1.0,10.2018,Add,9.880000e+08,6.310000e+08,0.08
10875,03-06-2025,Q2 2025,ZTS,FS,169.089996,169.732452,3149000.0,S,-652.0,15943.0,-4.0,1.0,0.1329,Add,1.083000e+09,7.180000e+08,0.09

In [6]:
dataset_prep['activity_act'].value_counts()

activity_act
Reduce    5814
Add       3454
Buy        948
Sell       660
Name: count, dtype: int64

In [7]:
dataset_prep['activity_act'] = dataset_prep['activity_act'].replace({
    'Reduce' : '0',
    'Sell' : '0',
    'Buy' : '1',
    'Add' : '1'
})
dataset_prep['activity_act'] = dataset_prep['activity_act'].astype(int)

dataset_prep['Trade Type'] = dataset_prep['Trade Type'].replace({
    'S' : '0',
    'P' : '1'
})

dataset_prep['Trade Type'] = dataset_prep['Trade Type'].astype(int)

# Reemplazo buy y add por 1, reduce y sell por 0
# cambio el tipo de dato a int
# en la columna Trade Type, reemplazo S por 0 y P por 1, manteniendo consistencia con el cambio en activity_act

In [8]:
dataset_prep['diferencia_cierre_vs_apertura'] = dataset_prep['Adj Close'] - dataset_prep['Open']

In [9]:
dataset_prep

,Date,quarter - year,Ticker,nombre_holding,Open,Adj Close,Volume,Trade Type,Qty,Owned,ΔOwn,insider_rating,activity_porc,activity_act,ebitda,netIncome,eps_surprise,diferencia_cierre_vs_apertura
0,25-08-2020,Q3 2020,AAPL,BRK,124.697502,121.419495,211495600.0,0,-265160.0,837374.0,-24.0,1.0,0.0370,0,1.823700e+10,1.267300e+10,0.03,-3.278008
1,02-10-2020,Q4 2020,AAPL,BRK,112.889999,109.936562,144712000.0,0,-257343.0,489260.0,-34.0,1.0,0.0605,0,3.688300e+10,2.875500e+10,0.26,-2.953438
2,02-10-2020,Q4 2020,AAPL,HC,112.889999,109.936562,144712000.0,0,-257343.0,489260.0,-34.0,1.0,1.0000,1,3.688300e+10,2.875500e+10,0.26,-2.953438
3,09-10-2020,Q4 2020,AAPL,BRK,115.279999,113.778809,100506900.0,0,-243431.0,110272.0,-69.0,1.0,0.0605,0,3.688300e+10,2.875500e+10,0.26,-1.501190
4,09-10-2020,Q4 2020,AAPL,HC,115.279999,113.778809,100506900.0,0,-243431.0,110272.0,-69.0,1.0,1.0000,1,3.688300e+10,2.875500e+10,0.26,-1.501190
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10871,11-02-2025,Q1 2025,ZTS,FS,171.179993,173.124924,2309400.0,0,-326.0,16919.0,-2.0,1.0,10.2018,1,9.880000e+08,6.310000e+08,0.08,1.944931
10872,19-02-2025,Q1 2025,ZTS,FS,156.539993,155.592926,4015300.0,0,-382.0,95006.0,0.0,1.0,10.2018,1,9.880000e+08,6.310000e+08,0.08,-0.947067
10873,10-03-2025,Q1 2025,ZTS,FS,169.649994,170.651581,3183800.0,0,-326.0,16593.0,-2.0,1.0,10.2018,1,9.880000e+08,6.310000e+08,0.08,1.001587
10874,11-03-2025,Q1 2025,ZTS,FS,170.619995,163.291107,3511400.0,0,-1210.0,11245.0,-10.0,1.0,10.2018,1,9.880000e+08,6.310000e+08,0.08,-7.328888
10875,03-06-2025,Q2 2025,ZTS,FS,169.089996,169.732452,3149000.0,0,-652.0,15943.0,-4.0,1.0,0.1329,1,1.083000e+09,7.180000e+08,0.09,0.642456

In [10]:
# dejar en el dataset la columna de adj close y eliminar open, close, high, low
#columnas_eliminadas_2 = ['Open','Volume', 'Owned', 'Qty']

columnas_eliminadas_2 = ['Open', 'Adj Close', 'Volume', 'Owned', 'Qty'] # <---- pipeline inicial 
dataset_prep = dataset_prep.drop(columns=columnas_eliminadas_2, errors='ignore')

In [11]:
dataset_prep

,Date,quarter - year,Ticker,nombre_holding,Trade Type,ΔOwn,insider_rating,activity_porc,activity_act,ebitda,netIncome,eps_surprise,diferencia_cierre_vs_apertura
0,25-08-2020,Q3 2020,AAPL,BRK,0,-24.0,1.0,0.0370,0,1.823700e+10,1.267300e+10,0.03,-3.278008
1,02-10-2020,Q4 2020,AAPL,BRK,0,-34.0,1.0,0.0605,0,3.688300e+10,2.875500e+10,0.26,-2.953438
2,02-10-2020,Q4 2020,AAPL,HC,0,-34.0,1.0,1.0000,1,3.688300e+10,2.875500e+10,0.26,-2.953438
3,09-10-2020,Q4 2020,AAPL,BRK,0,-69.0,1.0,0.0605,0,3.688300e+10,2.875500e+10,0.26,-1.501190
4,09-10-2020,Q4 2020,AAPL,HC,0,-69.0,1.0,1.0000,1,3.688300e+10,2.875500e+10,0.26,-1.501190
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10871,11-02-2025,Q1 2025,ZTS,FS,0,-2.0,1.0,10.2018,1,9.880000e+08,6.310000e+08,0.08,1.944931
10872,19-02-2025,Q1 2025,ZTS,FS,0,0.0,1.0,10.2018,1,9.880000e+08,6.310000e+08,0.08,-0.947067
10873,10-03-2025,Q1 2025,ZTS,FS,0,-2.0,1.0,10.2018,1,9.880000e+08,6.310000e+08,0.08,1.001587
10874,11-03-2025,Q1 2025,ZTS,FS,0,-10.0,1.0,10.2018,1,9.880000e+08,6.310000e+08,0.08,-7.328888
10875,03-06-2025,Q2 2025,ZTS,FS,0,-4.0,1.0,0.1329,1,1.083000e+09,7.180000e+08,0.09,0.642456

In [12]:
columnas_orden_2 = ['Date', 'quarter - year', 'Ticker', 'diferencia_cierre_vs_apertura', 'nombre_holding', 'activity_act', 'activity_porc']
# Crear el nuevo orden (primero las definidas, luego el resto en su orden original)
nueva_estructura = columnas_orden_2 + [col for col in dataset_prep.columns if col not in columnas_orden_2]

# Reordenar sobrescribiendo el mismo DataFrame
dataset_prep = dataset_prep[nueva_estructura]

columnas_cambio_nombre_2 = {'Trade Type' : 'Operacion_insider', 'ΔOwn' : 'resultado_operacion_insider'} # <----- pipeline inicial

dataset_prep = dataset_prep.rename(columns=columnas_cambio_nombre_2) # <----- pipeline inicial

dataset_prep

,Date,quarter - year,Ticker,diferencia_cierre_vs_apertura,nombre_holding,activity_act,activity_porc,Operacion_insider,resultado_operacion_insider,insider_rating,ebitda,netIncome,eps_surprise
0,25-08-2020,Q3 2020,AAPL,-3.278008,BRK,0,0.0370,0,-24.0,1.0,1.823700e+10,1.267300e+10,0.03
1,02-10-2020,Q4 2020,AAPL,-2.953438,BRK,0,0.0605,0,-34.0,1.0,3.688300e+10,2.875500e+10,0.26
2,02-10-2020,Q4 2020,AAPL,-2.953438,HC,1,1.0000,0,-34.0,1.0,3.688300e+10,2.875500e+10,0.26
3,09-10-2020,Q4 2020,AAPL,-1.501190,BRK,0,0.0605,0,-69.0,1.0,3.688300e+10,2.875500e+10,0.26
4,09-10-2020,Q4 2020,AAPL,-1.501190,HC,1,1.0000,0,-69.0,1.0,3.688300e+10,2.875500e+10,0.26
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10871,11-02-2025,Q1 2025,ZTS,1.944931,FS,1,10.2018,0,-2.0,1.0,9.880000e+08,6.310000e+08,0.08
10872,19-02-2025,Q1 2025,ZTS,-0.947067,FS,1,10.2018,0,0.0,1.0,9.880000e+08,6.310000e+08,0.08
10873,10-03-2025,Q1 2025,ZTS,1.001587,FS,1,10.2018,0,-2.0,1.0,9.880000e+08,6.310000e+08,0.08
10874,11-03-2025,Q1 2025,ZTS,-7.328888,FS,1,10.2018,0,-10.0,1.0,9.880000e+08,6.310000e+08,0.08
10875,03-06-2025,Q2 2025,ZTS,0.642456,FS,1,0.1329,0,-4.0,1.0,1.083000e+09,7.180000e+08,0.09

In [13]:
dataset_prep.to_csv(r"/home/srodriguezc/Simulador_de_compra_venta_de_acciones/Data/Merged/Dataset_final_prep.csv", index=False)